[package]
name = "nrdata-dl"
version = "0.1.0"
authors = ["Mário Queiroz <mario.al.queiroz@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.15.0"
filetime = "0.2.13"
lazy_static = "1.4.0"
regex = "1.4.2"
walkdir = "2.3.1"