[package]
name = "nrdata-dl"
version = "0.1.0"
authors = ["Mário Queiroz <mario.al.queiroz@gmail.com>"]
edition = "2018"

[dependencies]
dotenv = "0.15.0"
filetime = "0.2.14"
lazy_static = "1.4.0"
regex = "1.4.3"
reqwest = { version = "0.11.0", features = ["blocking", "json"] }
walkdir = "2.3.1"
