name: Rust Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Check for errors
      uses: actions-rs/cargo@v1
      with:
        command: check

    - name: Build
      if: ${{ success() }}
      uses: actions-rs/cargo@v1
      with:
        command: build

    - name: Run tests
      if: ${{ success() }}
      uses: actions-rs/cargo@v1
      with:
        command: test

    - name: Cache
      uses: Swatinem/rust-cache@v1

  additional:
    name: Additional Verification
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install latest stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy

    - name: Run linter
      uses: actions-rs/cargo@v1
      with:
        command: clippy

    - name: Check outdated dependencies
      uses: actions-rs/cargo@v1
      with:
        command: install cargo-outdated && cargo outdated -R

    - name: Look for security vulnerabilities
      uses: actions-rs/cargo@v1
      with:
        command: install cargo-audit && cargo audit

    - name: Check license compatibility
      uses: actions-rs/cargo@v1
      with:
        command: install cargo-lichking && cargo lichking check

    - name: Cache
      uses: Swatinem/rust-cache@v1
