name: Rust Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build and Test
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check for errors
      run: cargo check

    - name: Build
      if: ${{ success() }}
      run: cargo build

    - name: Run tests
      if: ${{ success() }}
      run: cargo test

  additional:
    name: Additional Verification
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run linter
      run: cargo clippy

    - name: Install plugins
      run: |
        cargo install cargo-audit
        cargo install cargo-outdated
        cargo install cargo-lichking

    - name: Look for security vulnerabilities
      run: cargo audit

    - name: Check license compatibility
      run: cargo lichking check
